Controllers/AdoptadosController.cs
using AppCuidandoPatitas.Datos;
using Microsoft.AspNetCore.Mvc;

namespace AppCuidandoPatitas.Controllers
{
    public class AdoptadosController : Controller
    {
        public DatosAdopciones DatosAdopciones = new();

        public IActionResult TraerListaAdoptadosVista()
        {
            var ListaAdopciones = DatosAdopciones.Listar();

            return View(ListaAdopciones);
        }

        public IActionResult AceptarAdopcion(int id)
        {
            var respuesta = DatosAdopciones.AceptarAdopcion(id);

            if (respuesta != 0)
            {
                TempData["SuccessMessage"] = "Se Acepto la adopcion.";
                return RedirectToAction("TraerListaAdoptadosVista");
            }
            else
            {
                return RedirectToAction("TraerListaAdoptadosVista");
            }


        }

        public IActionResult DeclinarAdopcion(int id)
        {
            var respuesta = DatosAdopciones.EliminarAdopcion(id);

            if (respuesta != 0)
            {
                TempData["SuccessMessage"] = "Se Elimino la adopcion.";
                return RedirectToAction("TraerListaAdoptadosVista");
            }
            else
            {
                return RedirectToAction("TraerListaAdoptadosVista");
            }


        }
    }
}

Controllers/AnimalesController.cs
using Microsoft.AspNetCore.Mvc;
using AppCuidandoPatitas.Datos;
using AppCuidandoPatitas.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace AppCuidandoPatitas.Controllers
{
    public class AnimalesController : Controller
    {
        readonly DatosAnimales DatosAnimales = new();
        readonly DatosDocumento DatosDocumento = new();
        readonly DatosEspecie DatosEspecie = new();
        readonly DatosAnimalEstado DatosAnimalEstado = new();

        public enum TipoDocumento
        {
            DocumentoAnimal = 2
        }

        [Authorize(Roles = "cp_admin, cp_rescatista, cp_adoptante")]
        public IActionResult traerMascotas()
        {
            var listaAnimales = DatosAnimales.Listar();
            return View("ListarAnimales", listaAnimales);
        }

        [Authorize(Roles = "cp_admin, cp_rescatista")]
        public IActionResult vistaIngresarMascota()
        {
            ViewBag.ListaEspecie = DatosEspecie.Listar();
            ViewBag.ListaDocumento = DatosDocumento.ListarDocumento((int)TipoDocumento.DocumentoAnimal);
            ViewBag.ListaAnimalEstado = DatosAnimalEstado.Listar();

            return View(); 
        }

        [Authorize(Roles = "cp_admin, cp_rescatista")]
        [HttpPost]
        public IActionResult ingresarMascota(ModelAnimales objMascota, IFormFile imagen)
        {
            if (imagen != null && imagen.Length > 0)
            {
                // Verificar si se ha enviado una foto y tiene contenido
                // Si hay una foto, la guardamos en la carpeta raíz
                objMascota.UserAlta = Convert.ToInt32(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value);
                var respuesta = DatosAnimales.Guardar(objMascota, imagen);

                if (respuesta == true)
                {
                    TempData["SuccessMessage"] = "La mascota se ingresó correctamente.";
                    return RedirectToAction("traerMascotas");
                }
                else
                {
                    TempData["ErrorMessage"] = "No se pudo ingresar la mascota. Intenta nuevamente.";
                    TempData["ModelErrors"] = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();

                    return RedirectToAction("vistaIngresarMascota");

                }
            }
            else
            {
                return RedirectToAction("vistaIngresarMascota", objMascota);
            }   
        }

        [Authorize(Roles = "cp_admin, cp_rescatista, cp_adoptante")]
        [HttpPost]
        public IActionResult adoptarMascota(int animalId)
        {
            var userId = Convert.ToInt32(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value);
            var respuesta = DatosAnimales.adoptarAnimal(animalId, userId);

            if (respuesta != 0)
            {
                TempData["SuccessMessage"] = "Se solicito la adopcion.";
                return RedirectToAction("traerMascotas");
            }
            else
            {
                return RedirectToAction("traerMascotas");
            }                 
        }

        [Authorize(Roles = "cp_admin, cp_rescatista")]
        [HttpPost]
        public IActionResult eliminarMascota(int animalId) 
        {
            var respuesta = DatosAnimales.eliminarAnimal(animalId);

             if (respuesta != 0)
            {
                return traerMascotas();
            }
            else
            {
                return View();
            }                 
        }

        [Authorize(Roles = "cp_admin, cp_rescatista")]
        [HttpPost]
        public IActionResult actualizarMascota(ModelAnimales objAnimal)
        {
            var respuesta = DatosAnimales.Editar(objAnimal);

             if (respuesta != true)
            {
                return RedirectToAction("traerMascotas");
            }
            else
            {
                return traerMascotas();
            }                 
        }

        [Authorize(Roles = "cp_admin, cp_rescatista")]
        public IActionResult modificarAnimalVista(int animalId)
        {
            var mascota = DatosAnimales.TraerUno(animalId);

            if(mascota != null)
            {               
                ViewBag.ListaEspecie = DatosEspecie.Listar();
                ViewBag.ListaDocumentos = DatosDocumento.ListarDocumento((int)TipoDocumento.DocumentoAnimal);
                ViewBag.ListaAnimalEstado = DatosAnimalEstado.Listar();

                return View(mascota);
            }
            else
            {
                return RedirectToAction("traerMascotas");
            }
        }

    }
}

Controllers/HomeController.cs
using AppCuidandoPatitas.Datos;
using AppCuidandoPatitas.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AppCuidandoPatitas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        readonly DatosHome datosHome = new();

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ModelHome modelHome = new();
            modelHome.ListaRescatados = datosHome.ListarRescatados();
            modelHome.ListaAdoptados = datosHome.ListarAdoptados();

            return View(modelHome);
        }

        public IActionResult IndexLogIn()
        {
            return View();
        }

        public IActionResult Nosotros()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GuardarMensaje(ModelHome objHome)
        {
            var respuesta = datosHome.Guardar(objHome);

            if (respuesta == true)
            {
                return RedirectToAction("Index");
            }
            else
            {
                
                return RedirectToAction("Index");
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Controllers/MensajesController.cs
using Microsoft.AspNetCore.Mvc;
using AppCuidandoPatitas.Datos;
using AppCuidandoPatitas.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace AppCuidandoPatitas.Controllers
{
    public class MensajesController : Controller
    {
        readonly DatosMensajes DatosMensajes = new();

        [Authorize(Roles = "cp_admin")]
        public IActionResult ListarMensajesView()
        {
            var listaMensajes = DatosMensajes.Listar();

            return View(listaMensajes);
        }

        [Authorize(Roles = "cp_admin")]
        public IActionResult VerMensajeView(int id)
        {
            var objMensaje = DatosMensajes.TraerUno(id);

            return View(objMensaje);
        }
    }
}

Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;
using AppCuidandoPatitas.Datos;
using AppCuidandoPatitas.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace AppCuidandoPatitas.Controllers
{
    public class UsuariosController : Controller
    {
        readonly DatosUsuarios DatosUsuarios = new();
        readonly DatosDocumento DatosDocumento = new();

        public enum TipoDocumento
        {
            DocumentoHumano = 1           
        }

        [Authorize(Roles = "cp_admin")]
        public IActionResult ListarUsuarios()
        {
            var listaUsuarios = DatosUsuarios.Listar();     

            return View(listaUsuarios);
        }

        public IActionResult NuevoUsuario()
        {
            var listaDocumentos = DatosDocumento.ListarDocumento((int)TipoDocumento.DocumentoHumano);
            ViewBag.ListaDocumentos = listaDocumentos;

            return View();
        }

        [Authorize(Roles = "cp_admin, cp_rescatista, cp_adoptante")]
        [HttpPost]
        public IActionResult GuardarUsuario(ModelUsuarios objUsuario)
        {
            var respuesta = DatosUsuarios.Guardar(objUsuario);

            if(respuesta == true)            
            {               
                return RedirectToAction("listarUsuarios");
            }
            else
            {             
                return View();
            }
        }

        [Authorize(Roles = "cp_admin, cp_rescatista, cp_adoptante")]
        public IActionResult TraerUsuario(int id) {

            var usuario = DatosUsuarios.TraerUno(id);

            if (usuario != null)
            {
                var listaDocumentos = DatosDocumento.ListarDocumento((int)TipoDocumento.DocumentoHumano);
                ViewBag.ListaDocumentos = listaDocumentos;
                return View("VerUser", usuario);
            }
            else
            {
                return View();
            }
        }

        [Authorize(Roles = "cp_admin, cp_rescatista, cp_adoptante")]
        public IActionResult DesactivarUser(int id)
        {

            var userBajaId = Convert.ToInt32(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value);
            var usuario = DatosUsuarios.Baja(id, userBajaId);

            if (usuario)
            {
                TempData["Mensaje"] = "Usuario dado de baja";
                return RedirectToAction("listarUsuarios");
            }
            else
            {
                TempData["Mensaje"] = "No existe el usuario";
                return RedirectToAction("listarUsuarios");
            }
        }

        [Authorize(Roles = "cp_admin, cp_rescatista, cp_adoptante")]
        public IActionResult EditarUsuarioView(int id)
        {
            var usuario = DatosUsuarios.TraerUno(id);          

            if (usuario != null)
            {
                
                var listaDocumentos = DatosDocumento.ListarDocumento((int)TipoDocumento.DocumentoHumano);
                ViewBag.ListaDocumentos = listaDocumentos;
                return View(usuario);
            }
            else
            {
                
                return RedirectToAction("listarUsuarios");
            }
        }

        [Authorize(Roles = "cp_admin, cp_rescatista, cp_adoptante")]
        [HttpPost]
        public IActionResult Editar(ModelUsuarios objUsuario)
        {

            var respuesta = DatosUsuarios.Editar(objUsuario);

            if (respuesta)
            {
                TempData["SuccessMessage"] = "Exito - Usuario editado exitosamente.";
                return RedirectToAction("ListarUsuarios");
            }
            else
            {             
                TempData["SuccessMessage"] = "Error - Error al editar el usuario.";
                return RedirectToAction("ListarUsuarios");
            }
        }



    }
}

Views/Home/IndexLogIn.cshtml
@using Microsoft.AspNetCore.Identity;
@using Microsoft.AspNetCore.Authentication.Cookies;

@{
    ViewData["Title"] = "HOME INDEX";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container" style="display: flex; flex-wrap: wrap; justify-content: start; gap: 10px; margin-top: 20px;">

    @if (User.IsInRole("cp_admin") || User.IsInRole("cp_rescatista"))
    {
        <a class="btn btn-primary btn-lg" style="width: 230px; padding: 2%;" asp-area="" asp-controller="Usuarios" asp-action="ListarUsuarios">
            <h2 class="text-center">
                LISTA DE<br>
                USUARIOS
            </h2>
        </a>
    }

    @if (User.IsInRole("cp_admin"))
    {
        <a class="btn btn-info btn-lg" style="width: 230px; padding: 2%;" asp-area="" asp-controller="Mensajes" asp-action="ListarMensajesView">
            <h2 class="text-center">
                LISTA DE<br>
                MENSAJES
            </h2>
        </a>
    }

    @if (User.IsInRole("cp_admin") || User.IsInRole("cp_rescatista") || User.IsInRole("cp_adoptante"))
    {
        <a class="btn btn-success btn-lg" style="width: 230px; padding: 2%;" asp-area="" asp-controller="Animales" asp-action="traerMascotas">
            <h2>
                LISTA DE<br>
                PATITAS 🐾
            </h2>
        </a>
    }

    @if (User.IsInRole("cp_admin") || User.IsInRole("cp_rescatista"))
    {

        <a class="btn btn-warning btn-lg" style="width: 230px; padding: 2%;" asp-area="" asp-controller="Animales" asp-action="vistaIngresarMascota">
            <h2>
                INGRESAR<br>
                PATITA 🐾
            </h2>
        </a>
    }

    @if (User.IsInRole("cp_admin") || User.IsInRole("cp_rescatista"))
    {

        <a class="btn btn-warning btn-lg" style="width: 230px; padding: 2%;" asp-area="" asp-controller="Adoptados" asp-action="TraerListaAdoptadosVista">
            <h2>
                LISTA DE<br>
                ADOPCIONES
            </h2>
        </a>
    }


</div>

Views/Home/Nosotros.cshtml
@{
    ViewData["Title"] = "NOSOTROS";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f9;
            margin: 0;
            padding: 0;
            text-align: center;
        }

        h1 {
            color: #333;
            margin-top: 20px;
            font-size: 2.5em;
        }

        .row {
            display: flex;
            justify-content: center;
            flex-wrap: wrap;
            margin: 20px;
            gap: 20px;
        }

        .linkedin-card {
            width: 250px;
            border: 2px solid #0077b5;
            border-radius: 10px;
            background-color: #ffffff;
            padding: 20px;
            text-align: center;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            transition: transform 0.2s, box-shadow 0.2s;
        }

            .linkedin-card:hover {
                transform: translateY(-5px);
                box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
            }

            .linkedin-card img {
                border-radius: 50%;
                width: 100px;
                height: 100px;
                object-fit: cover;
                margin-bottom: 15px;
                border: 3px solid #0077b5;
            }

            .linkedin-card h3 {
                margin: 10px 0 5px;
                font-size: 1.2em;
                color: #0077b5;
            }

            .linkedin-card p {
                margin: 5px 0 15px;
                font-size: 0.95em;
                color: #666;
            }

            .linkedin-card a {
                text-decoration: none;
                color: #ffffff;
                background-color: #0077b5;
                padding: 10px 15px;
                border-radius: 5px;
                font-weight: bold;
                font-size: 0.9em;
            }

                .linkedin-card a:hover {
                    background-color: #005582;
                }
    </style>

    <h1>Nosotros somos Cuidando Patitas</h1>

    <div class="row">
        <div class="linkedin-card">
            <img src="../Nosotros/foto_andres_antivero.png" alt="Foto de Andres Antivero">
            <h3>Andrés Antivero</h3>
            <p>Líder Técnico</p>
            <a href="https://www.linkedin.com/in/andres-oscar-antivero/" target="_blank">Ver en LinkedIn</a>
        </div>

        <div class="linkedin-card">
            <img src="../Nosotros/foto_lisset_castillo.jpeg" alt="Foto de Lisset Castillo">
            <h3>Lisset Castillo</h3>
            <p>Desarrolladora</p>
            <a href="https://www.linkedin.com/in/lisett-castilloqautomation/" target="_blank">Ver en LinkedIn</a>
        </div>

    <div class="linkedin-card">
        <img src="../Nosotros/foto_jose_martinez.jpeg" alt="Foto de Jose Martinez">
        <h3>José Martínez</h3>
        <p>Desarrollador</p>
        <a href="https://www.linkedin.com/in/type-taretto/" target="_blank">Ver en LinkedIn</a>
    </div>

        <div class="linkedin-card">
            <img src="../Nosotros/foto_emmanuel_espinoza.jpeg" alt="Foto de Emmanuel Espinoza">
            <h3>Emmanuel Espinoza</h3>
            <p>Analista Funcional</p>
            <a href="https://www.linkedin.com/in/emmanuelespinozarios/" target="_blank">Ver en LinkedIn</a>
        </div>
    </div>